spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  jpa:
    hibernate:
      ddl-auto: none